import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const grammarPath = resolve(process.argv[1] ?? '', '../src/TTR.g4');
const outputPath = resolve(process.argv[2] ?? '', '../src/generated/property-map.ts');

const grammar = readFileSync(grammarPath, 'utf-8');

interface PropertyInfo {
  name: string;
  type: string;
}

interface PropertyMap {
  [kind: string]: PropertyInfo[];
}

const kindMap: PropertyMap = {};

const propertyRuleRegex = /^(?<kind>\w+Property)\s*:\s*(?<props>[\w\d|]+)\s*;/gm;

let match: RegExpExecArray | null;
while ((match = propertyRuleRegex.exec(grammar)) !== null) {
  const kind = match.groups!.kind;
  const props = match.groups!.props;

  const defKind = kind.replace('Property', '');
  const propertyNames = props
    .split('|')
    .map((p: string) => p.trim())
    .filter((p: string) => p.length > 0);

  kindMap[defKind] = propertyNames;
}

const typeMap: Record<string, string> = {
  description: 'string',
  tags: 'list of strings',
  version: 'string',
  primaryKey: 'list of strings',
  columns: 'list of column definitions',
  indices: 'list of index definitions',
  constraints: 'list of constraint definitions',
  definitionSql: 'string',
  type: 'data type',
  optional: 'boolean',
  isKey: 'boolean',
  searchable: 'boolean',
  indexed: 'boolean',
  from: 'reference',
  to: 'reference',
  parameters: 'list of parameter definitions',
  resultColumns: 'list of column definitions',
  labelPlural: 'string',
  nameAttribute: 'reference',
  name: 'identifier',
  codeAttribute: 'reference',
  aliases: 'list of strings',
  attributes: 'list of attribute definitions',
  cardinality: 'object',
  join: 'list',
  entity: 'reference',
  attribute: 'reference',
  relation: 'reference',
  fk: 'reference',
  target: 'object',
  whereFilter: 'object',
  language: 'language',
  sourceText: 'string',
  length: 'number',
  precision: 'number',
  label: 'localized string',
  paramLabel: 'string',
  direction: 'identifier',
  displayLabel: 'localized string',
  roles: 'list of identifiers',
  valueLabels: 'value labels',
  role: 'reference',
  keywords: 'localized string list',
  patterns: 'list of strings',
  descriptions: 'localized string list',
  examples: 'list of strings',
  fuzzy: 'boolean',
  search: 'search block',
};

const allKinds = [
  'model',
  'table',
  'view',
  'column',
  'index',
  'constraint',
  'fk',
  'procedure',
  'entity',
  'attribute',
  'relation',
  'er2dbEntity',
  'er2dbAttribute',
  'er2dbRelation',
  'query',
  'role',
  'er2cncRole',
];

let output = `// AUTO-GENERATED by packages/grammar/scripts/extract-property-map.ts
// Do not edit manually — regenerate with: pnpm --filter @modeler/grammar prebuild

export type DefinitionKind =
`;

for (let i = 0; i < allKinds.length; i++) {
  output += `  | '${allKinds[i]}'`;
}
output += ';\n\n';

output += 'export interface PropertyInfo {\n  name: string;\n  type: string;\n}\n\n';

output += 'export const PROPERTY_MAP: Record<DefinitionKind, PropertyInfo[]> = {\n';
for (const kind of allKinds) {
  const props = kindMap[kind] ?? [];
  const infos = props.map((p) => `{ name: '${p}', type: '${typeMap[p] ?? 'unknown'}' }`);
  output += `  ${kind}: [${infos.join(', ')}],\n`;
}
output += '};\n';

console.log('Writing to', outputPath);
const { writeFileSync, mkdirSync } = await import('node:fs');
mkdirSync(resolve(outputPath, '..'), { recursive: true });
writeFileSync(outputPath, output);
console.log('Done');